#!/bin/bash
countCpu=0
countIdle=0
flagIdle=0
flagCpu=0
echo ----------- FREQ TIME---------------------------
while (( $countCpu != 8 ))
    do
		cd /sys/devices/system/cpu/cpu$countCpu/cpufreq/stats 2> /dev/null
		if (( $? != 0 ))
		then
			flagIdle=1
			echo cpu $countCpu error occured
		else
			echo cpu $countCpu state $countIdle
#				echo name $(cat name)                
#				echo desc $(cat desc)
#				echo disable $(cat disable)
#				echo latency $(cat latency)
#				echo power $(cat power)
#				echo residency $(cat residency)
#				echo usage $(cat usage) 
#				echo time $(cat time)
			#cat name                
			#cat desc
			#cat disable
			#cat latency
			#cat power
			#cat residency
			#cat usage 
			cat time_in_state
			echo --------------------------------------
		fi
    countCpu=$(( $countCpu + 1 ))
    countIdle=0
	done
	echo ------------ FREQ TIME --------------------------
